-- Authors: Ajinkya Vijay Sonawane, Sidharth Purohit
DROP TABLE IF EXISTS NFT_Log;
DROP TABLE IF EXISTS Account_Log;
DROP TABLE IF EXISTS Login_Log;
DROP TABLE IF EXISTS Audit CASCADE;
DROP TABLE IF EXISTS Currency_holds;
DROP TABLE IF EXISTS Wallet_has;
DROP TABLE IF EXISTS Sell_TXN;
DROP TABLE IF EXISTS Buy_TXN;
DROP TABLE IF EXISTS Transactions_contains;
DROP TABLE IF EXISTS NFT_owned;
DROP TABLE IF EXISTS NFT_created;
DROP TABLE IF EXISTS NFT;
DROP TABLE IF EXISTS Financial_Information_contains;
DROP TABLE IF EXISTS Login_requires;
DROP TABLE IF EXISTS Account CASCADE;